site_name: My Docs

theme: readthedocs

plugins:
    - search
    - doxygen-snippets:
        # doxygen-source: src
        # api-path: api
        # debug: False
        # hints: True
        # full-doc: True