site_name: My Docs

theme: readthedocs

docs_dir: docs

# plugins:
    # - search
    # - doxygen-snippets:
        # doxygen-source: src
        # api-path: api
        # debug: False
        # hints: True
        # full-doc: True